### ISSUE TITLE
Please update CRAN

### ISSUE THREAD

**Issue by ljos** [mimno/RMallet#14]
Hi -

The CRAN version of mallet is not updated, so `mallet.topic.labels` always gives labels with the 3 top words instead of the give `num.top.words`. If I use devtools to download mallet it does the right thing. 

Thank you!

Regards,
Bjarte

**Comment by mimno** [comment]
Thank you for writing! We're currently transitioning management of the CRAN package, expect more frequent updates soon.

**Comment by MansMeg** [comment]
Now on CRAN. Yay!
