### ISSUE TITLE
Is it possible to load a topic model?

### ISSUE THREAD

**Issue by victorlaerte** [mimno/RMallet#15]
I've used Mallet to generate and train my topics. I saved the model in `topic.model` file. Right now I'm trying to load this topic in RMallet like it's possible to do with Java API `ParallelTopicModel.read(new File("data/topic-model.dat"));` but I could find anything about it.

**Comment by MansMeg** [comment]
It should now be possible in the new version on CRAN. Please check the vignette if that is what you need.
