### ISSUE TITLE
Bug in mallet.word.freq()?

### ISSUE THREAD

**Issue by kshirley** [mimno/RMallet#2]
Hi,

I think there might be a bug in the way terms are counted using the function mallet.word.freq(). I've pasted code below with a toy example.

It looks like the actual fitting of the LDA model is fine, and the term frequencies extracted from the function mallet.topic.words(..., smoothed =  FALSE, normalized = FALSE) are correct. But they don't match the frequencies from the second columns of mallet.word.freq().

On a large data set, I found that the frequency of the first term in the vocabulary was off by a large amount, and the rest of the frequencies were only off by 1 or 2, for example. Could it be an issue with the indexing of vectors (since Java indices start with 0, and R indices start with 1?)

best,
kenny

PS Sorry I can't fix it myself and send a pull request -- I have no idea how to deal with binding R to Java!

Example code:

``` r
rm(list=ls())
```

load mallet

``` r
library(mallet)
```

Create a toy data set with 5 short documents:

``` r
documents <- data.frame(id=as.character(1:5), text=c("this is an example document", "here is another example document", 
                                       "another small example",
                                       "this document is quite long compared to the other examples", 
                                       "finally here is the last example"),
                        stringsAsFactors=FALSE)
```

create a stop word file:

``` r
write.table(data.frame(stop=c("the", "of")), file="stopwords-example.txt", quote=F, row.names=F, col.names=F)
```

Create a mallet instance list object.

``` r
mallet.instances <- mallet.import(documents$id, documents$text, 
stoplist.file = "stopwords-example.txt", token.regexp = "[\\p{L}]+")
```

Create a topic trainer object.

``` r
topic.model <- MalletLDA(num.topics=2)
```

Load our documents. We could also pass in the filename of a saved instance list file that we build from the command-line tools.

``` r
topic.model$loadDocuments(mallet.instances)
```

Get the vocabulary, and some statistics about word frequencies.
These may be useful in further curating the stopword list.

``` r
vocabulary <- topic.model$getVocabulary()
word.freqs <- mallet.word.freqs(topic.model)
```

Optimize hyperparameters every 20 iterations, after 50 burn-in iterations.

``` r
topic.model$setAlphaOptimization(20, 50)
```

Now train a model.

``` r
topic.model$train(200)
```

Compute the table of topic assignments to documents and terms:

``` r
doc.topics <- mallet.doc.topics(topic.model, smoothed=FALSE, normalized=FALSE)
topic.words <- mallet.topic.words(topic.model, smoothed=FALSE, normalized=FALSE)
```

Look at the mis-match between term frequencies computed using mallet.word.freqs() (which I believe is wrong) and the term frequencies coming out of the fit of the LDA model (which is correct):

``` r
cbind(correct.counts = apply(topic.words, 2, sum), word.freqs)
```

**Comment by clarkest** [comment]
I've run into the same bug in a dataset I'm working with--mismatched frequencies between the two approaches.  Further, `mallet.word.freqs()` returns many zero counts for `term.freq` and for `doc.freq`.  This, combined with very high correlation between the two approaches (0.9993 in my case) makes me think it's not a mis-indexing issue.

I get the same results when using `topic.model$getWordFrequencies()` directly, so the issue must be upstream in the java code itself.  

Possible culprits:
(1) a bug in the counting done in https://github.com/mimno/Mallet/blob/master/src/cc/mallet/topics/RTopicModel.java.  But I don't see anything obvious here.
(2) some transformation in the feature sequence that occurs that is different than we expect, but normal code operation. 
(3) something odd with feature sequence creation (way beyond my pay grade) 

I believe this method is meant as a convenience method, and I get similar run times for both `model$getWordFrequencies()` and `colSums(mallet.topic.words(topic.model, normalized=F), na.rm=TRUE)`.  So the `term.freq` could be replaced with this code, but I'm not sure how to replace `doc.freq`

**Comment by clarkest** [comment]
Here's what I'm using as a work-around for the `term.freq`:
```
words <- mallet.word.freqs(topic.model)
words$term.freq <- rowSums(mallet.topic.words(topic.model, normalized=F), na.rm=TRUE)
```

**Comment by MansMeg** [comment]
Finally, this has now been fixed with the new CRAN version.
