### ISSUE TITLE
RMallet not usable with Java 1.8 on OSX due to non-working rJava

### ISSUE THREAD

**Issue by conjugateprior** [mimno/RMallet#3]
There may not be anything you can do about this, but fyi RMallet won't work for Yosemite folk if they've got the current Oracle Java (1.8) installed. Proximately it seems to be an rJava problem (see [this bug](https://github.com/s-u/rJava/issues/37), although that package's developer thinks it's Oracle's fault.)  In any case, `library(mallet)` or `library(rJava)` make the OS popup to suggest a Java 6(!) download and at the same time sink your R session.

There is a lot of discussion about load paths and `R CMD javareconf` around this topic, but nothing so far that suggests a fix.

**Comment by MansMeg** [comment]
This should now be working, I think.
