### ISSUE TITLE
number of tokens in each document of the corpus

### ISSUE THREAD

**Issue by gpcoursera** [mimno/RMallet#7]
Hi,

For visualization purpose I need to compute the vector 
doc.length = a vector containing the number of tokens in each document of the corpus.

Question: how can I construct such a vector from a MALLET instance list (mallet.import) directly in R using RMallet?

More precisely, if I train a model with malletLDA and store the object in a var called model, 
I can access to model$instances that gives me the list of instances the model used for training. But I don't know how to access and manipulate each of the instance object (individually) contained in the instance list and therefore compute the number of tokens per document.

Hope I'm clear ...

Thanks a lot.
G.

**Comment by mimno** [comment]
The easiest way is to use mallet.doc.topics with no normalization and no smoothing to get the matrix of doc/topic counts, then use rowSums(). There will be a simpler way in the next version.

**Comment by gpcoursera** [comment]
Thank you David.
But I was wondering if there was a way to count the number of words just after the preprocessing (pipes) and not relying on the result of the decomposition namely mallet.doc.topics.
My goal is to count the numbers of words per document in the actual input.
But I realize it might be difficult to do within Rmallet. Maybe looking at the Java code directly?
All the best
G.

**Comment by MansMeg** [comment]
I suggest you can use the tm package in R (information  [here](https://cran.r-project.org/web/packages/tm/vignettes/tm.pdf)) if you want to get the number of tokens. Just remember to tokenize in the same way as you do using the RMallet/Mallet package.

**Comment by MansMeg** [comment]
Should we close this issue or do you, @gpcoursera , still need this?
